### ISSUE TITLE
IdentifierError during update to streamflow database

### ISSUE THREAD

**Issue by corviday** [pacificclimate/modelmeta#80]
The following error occurs when updating a database from version 614911daf883 to version 12f290b63791 using alembic:

```
sqlalchemy.exc.IdentifierError: Identifier 'data_file_variables_dsg_time_series_x_stations_data_file_variable_dsg_ts_id_id_fkey' exceeds maximum length of 63 characters
```

Downgrading sqlalchemy to version 1.2.0 from version 1.3.3 fixes this issue. So the probable long-term solution is just to pin sqlalchemy at ~1.2 in requirements.txt. 

I was unable to find any explicit mention of adding a chartacter limit to identifiers in the [sqlalchemy changelogs](https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/changelog/changelog_13.rst), though change 3989 seems like it might be relevant.

**Comment by jameshiebert** [comment]
Why don't we change the name of this index to be more concise? This is probably running up against Postgres's [maximum identifier length](https://www.postgresql.org/docs/9.3/runtime-config-preset.html). This value is *technically* is configurable, but why not make this reasonable so that it doesn't require tweaking PG's run time config?

**Comment by rod-glover** [comment]
As the author of this august and explicit identifier, I must ... agree. What was I thinking?

**Comment by jameshiebert** [comment]
Great! Have we actually run this migration? If not, fixing it is easy. If we have, things get a bit trickier...

**Comment by corviday** [comment]
The only place the migration has been run is on various test databases. It hasn't been run on anything real yet.
